name: Integration

on:
  push:
    branches:
      - main
      - feature/**
      - bugfix/**
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  terraform-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Docker image
        run: docker build -t local/terraform-provider-validatefx -f Dockerfile .

      - name: Run integration scenario
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/integration":/workspace \
            -w /workspace \
            local/terraform-provider-validatefx \
            /bin/sh -ec 'terraform init -input=false && terraform apply -auto-approve -input=false && terraform destroy -auto-approve -input=false'

      - name: Upload Terraform logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: terraform-logs
          path: integration/.terraform
          if-no-files-found: ignore
